---
#
# tasks file for codecap.kubectl
#

- include: prerequisites.yml
  when:    kubectl_conf.ensure_prerequisites
- include: get-last-version.yml
- include: download.yml
- include: completion.yml
  when:    kubectl_conf.install_completion
